### PR TITLE
Landing "THE MET"

### PR DESCRIPTION
**Pull request by mdm-21**
[DEMO LINK](https://mdm-21.github.io/layout_miami/)

### CODE REVIEW

**Review by AlisaVlasova — CHANGES_REQUESTED** [review]
Great job)
few comments

1. reset form field on submit
2. add smooth transition to all interactive elements
3. add some scale hover effects on images

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. Element's hover effects shoudn't affect its siblings
2.  Make all fields required

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Pictures should not overlap each other
image
image

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Good job, just  the cursor should become a pointer over this button
image

**Review by SanyaBratashchuk — APPROVED** [review]
Add hover effects for these links (change color for example)
image

**Pull request closed without merging**
