### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by serhiicode**
- [DEMO LINK](https://serhiicode.github.io/layout_miami/)

### CODE REVIEW

**Review by stanislav-topikha — CHANGES_REQUESTED** [review]
Recheck ALL points from the checklist ⬇️ 

https://github.com/mate-academy/layout_miami/blob/master/checklist.md

**Comment by serhiicode** [comment]
я не розумію як зробити, джава скріпт не проходив ще:
15. Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
Also, recheck ALL points from the [checklist](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
404 after click on logo
image
And check your project with checklist

**Review by SanyaBratashchuk — APPROVED** [review]

**Pull request closed without merging**
