### PR TITLE
 layout_miami

### PR DESCRIPTION
**Pull request by EkaterinaBessonnaya**
[DEMO LINKA](https://EkaterinaBessonnaya.github.io/bose_landing/)

### CODE REVIEW

**Review by qoa11a — CHANGES_REQUESTED** [review]
good job! 👍 
few fixes:
1. click on the cross in the burger menu shouldn't send the user to the 404 page
2. looks like this section should be a little bit less in height

**Comment by polosanya** [comment]
Don't close the PR. Just push the changes and ask for re-review when you are ready

**Comment by EkaterinaBessonnaya** [comment]
i need close this PR becouse this choosen wrong branches

**Comment by polosanya** [comment]
You can just delete it then

**Pull request closed without merging**
