### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pawelnowicki87**

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Hi, there are no demo link here, also you need to add the demo link to the PR description
image

**Comment by pawelnowicki87** [comment]
[DEMO LINK](https://pawelnowicki87.github.io/layout_miami/)

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your page
1. Need to add icons to the header as on the design
image

2. Add a favicon and actual title on the page
image

3. Need to fix the placeholder text position as on the design
image

Keep going with the desktop version

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
To improve:
1. Need to remove the scroll when this menu is open
image

2. The user will not be able to change the size of this field
image

3. These elements should be links, also you need to add the hover effects here
image

4. Need to change the autocomplete styles for the imputs
image

5. Add the cursor pointer for the all clickable elements
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! 
Screenshot 2024-01-15 at 14 10 09
Check styles here
Screenshot 2024-01-15 at 14 10 03
A user should be able to click on the phone number 
Screenshot 2024-01-15 at 14 09 34
Check styles for tablets 
Screenshot 2024-01-15 at 14 09 18
Consider removing the default outline 
Screenshot 2024-01-15 at 14 08 50
Check the text alignment 
Screenshot 2024-01-15 at 14 08 40
A user should be able to scroll the menu

**Pull request closed without merging**
