### PR TITLE
firs commit,only test

### PR DESCRIPTION
**Pull request by SerhiiNalyvaiko**
[DEMO LINK](https://SerhiiNalyvaiko.github.io/layout_MET)

### CODE REVIEW

**Review by tetiana-ivanchenko — CHANGES_REQUESTED** [review]
request re-review when your layout will be ready

**Review by OleziO — CHANGES_REQUESTED** [review]
Prevent scrolling the page when the menu is opened. 
image

Fix hover 
image

Open in a new tab 
image

Prevent page reloading after form submission.

Demo: 
image
Design: 
image

Design: 
image
Demo:
image


Design: 
image
Demo: 
image


Design: 
image
Demo: 
image

**Review by ivanchuk-yurii — CHANGES_REQUESTED** [review]
image shouldn't be on each other. form shouldn't reload page
image
this button shouldn't be link to google maps
image

**Review by tetiana-ivanchenko — CHANGES_REQUESTED** [review]
1. transition on hover should be when you remove mouse from the element too
2. all external links should open in the new tab 
image

3. cursor pointer
image
4.

**Comment by TarasHoliuk** [comment]
1. The middle images row should contain square shape images (i.e height of the image-container should be 100% for them) in the tablet view
image

2. Set `object-position: right` in the mobile view for this image
image

3. This button should have the same style on hover as the `Send` button, check UI Kit section in the Figma mockup:
image
image

4. These links don't have transition:
image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Very good job :+1: 
A few things still should be fixed (but it should be easy to fix - I've written solutions for some of them)

**Review by AlisaVlasova — CHANGES_REQUESTED** [review]
Almost done!)
Check spacing between the last block and footer on mobile
image

**Review by etojeDenys — CHANGES_REQUESTED** [review]
looks awesome

**Review by etojeDenys — APPROVED** [review]

**Pull request closed without merging**
