### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by patryk177m**
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

### CODE REVIEW

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Review by choeqq — CHANGES_REQUESTED** [review]
1. Menu isn't working properly
2. Please add interactivity to everything related to email / phone / address - [checklist](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)
3. Logo should take us to `home` not `header`
4. Please add hover on buttons
5. Footer image should be stretched on whole page width like hero image
6. Your form should not reload the page and take us to 405, additionaly please provide form validation - we don't want to sent empty requests

Overall looks good, but few adjustments are needed 🚀

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Review by JoyCoffeeAddict — COMMENTED** [review]
1. Add `hover`  to images according to checklist point 10.

2. Add some padding to inputs 
image

3. This `hover` effect is unusual, it does not match the whole page design, try to come up with some other idea. Menu should also stretch on 100% viewport's height
image

4. Scrolling according to checklist point 16.

5. Form is not sending any request, also there is no validation on inputs

**Review by JoyCoffeeAddict — CHANGES_REQUESTED** [review]
1. The design on tablets should be different than on mobile
image

2. On tablets form should remind pc version, not mobile version 
image

3. Read previous comment by Kacper and apply them.

Good job

**Review by choeqq — CHANGES_REQUESTED** [review]
Waiting for any updates @patryk177m 👀

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Review by choeqq — CHANGES_REQUESTED** [review]
1. Address should redirect us to Google Maps 
image
2. Please add form validation - we don't want to send empty reuqests
3. Please disable horizontal scrolling 
4. Add placeholder to your textfield 
image

**Comment by PatrykMajewski177** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Comment by patryk177m** [comment]
[DEMO LINK](https://patryk177m.github.io/layout_miami/)

**Review by JoyCoffeeAddict — APPROVED** [review]
1. Add some padding to inputs
image

You only have one small issue, so I believe that you can fix it on your own.

**Pull request closed without merging**
