### PR TITLE
Made landing 

### PR DESCRIPTION
**Pull request by mira1zu**
- [DEMO LINK](https://mira1zu.github.io/layout_miami/)

### CODE REVIEW

**Review by jstmpelowycz — CHANGES_REQUESTED** [review]
Good job!
Make sure you fix the following issues:

- go through the checklist one more time
- in the menu, hover effects are too long, and damage UX, also it's required that all effects over the page are of the same transition duration
- phone number appearing on hover for the phone icon isn't in its proper place
- to enhance UX, make your form field get cleared on submit

**Comment by mykola-koval** [comment]
image
header should be `100vh`

**Comment by mykola-koval** [comment]
image
i see this when i click on a logo in header
it should not redirect to any external page

**Review by mykola-koval — APPROVED** [review]
fix the remaining issues and you're good to go!

**Pull request closed without merging**
