### PR TITLE
Develop MET landing

### PR DESCRIPTION
**Pull request by sergey-lipikhin**
- [DEMO LINK](https://sergey-lipikhin.github.io/layout_miami/)

### CODE REVIEW

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
Icons are too big on desktop

Other is good

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
Don't forget to change title and add favicon

Something wrong with this red text, double check with design
Screenshot 2023-02-10 at 18 17 21

This small text block is too large, check in design (probably pseudoelement is overkill now, it bring more problems that benefits)
Screenshot 2023-02-10 at 18 17 54

Icons should be smaller, check in design
Screenshot 2023-02-10 at 18 20 25

Don't forget to add hover effects to images, cards links and buttons

**Comment by BozhenaBodnar** [comment]
your landing have good look!! well-done

**Review by BozhenaBodnar — APPROVED** [review]

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
Let's add transition to phone numbers block in header

I guess this is really strange solution for color to this link on hover, please fix it
Screenshot 2023-02-11 at 12 43 34

This small description text shouldn't be wider than heading, please check on design
Screenshot 2023-02-11 at 12 45 01

`View all exhibition` button redirects to top of the page and it's not logical, better to redirect to another block from this page, or to third party resource

These cards looks too wide on tablets
Screenshot 2023-02-11 at 12 47 37

**Review by Andr1yK — APPROVED** [review]

**Pull request closed without merging**
