### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by crash2bash**
По svg прошелся утилитой svgo

[DEMO LINK](https://crash2bash.github.io/layout_miami/)

### CODE REVIEW

**Comment by earthhuman41** [comment]
Do i need watch all 41 files?
Screen Shot 2020-03-12 at 12 28 27 PM

**Comment by earthhuman41** [comment]
will be better if you will align it by the same line
Screen Shot 2020-03-12 at 12 29 12 PM

**Comment by earthhuman41** [comment]
I think you may hide menu already on tablets
Screen Shot 2020-03-12 at 12 30 52 PM

**Comment by crash2bash** [comment]
> Do i need watch all 41 files?
> Screen Shot 2020-03-12 at 12 28 27 PM

Хмм, ну это по желанию, конечно))

**Comment by earthhuman41** [comment]
remove all blue outlines and replace them by custom with :focus
Screen Shot 2020-03-12 at 12 32 11 PM

**Comment by earthhuman41** [comment]
Не поудалял все outline

**Pull request closed without merging**
