### PR TITLE
add header and menu blocks

### PR DESCRIPTION
**Pull request by hulchak**
https://hulchak.github.io/layout_miami

### CODE REVIEW

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good start! Keep it up :)

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
keep going. Do not forget add scale effect for images on hover

**Review by OleziO — CHANGES_REQUESTED** [review]
Remove the redirect and refresh the page after submitting.
image

Remove scrolling
image

Align picture
image
Design: 
image


Design: 
image
Demo:
image

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Almost good! 

Add attribute target='_blank'  to address link to open it on new tab
image

**Review by TarasHoliuk — APPROVED** [review]
Looks amazing :fire: 
Approved :heavy_check_mark:

**Pull request closed without merging**
