### PR TITLE
Add task solution

### PR DESCRIPTION
**Pull request by EugeneSherepa**
[DEMO LINK](https://EugeneSherepa.github.io/layout_miami/)

### CODE REVIEW

**Review by silchyn — CHANGES_REQUESTED** [review]
image

**Review by 33Orange — CHANGES_REQUESTED** [review]
Some comments:
- You need add hover effect to links in `contact` section (phone, email, address). 
`[Checklist p4: Change text color on hover for phone, email and address] `
- You must add a transition to the Google map at the address, when you click on the address in contact section. And don't forget about `target="_blank"`.
`[Checklist p7: When clicking on any location / address - prevent errors and make it to open location in Google Maps]`
- Your pictures decrease on hover :) `[Checklist p8. Pictures in Gallery should increase on hover]`
- The menu should go on top of everything on the site. If the menu is open and I press `tab`, then I can see the content.
image

- All fields in the form must be `required`. Now they are all optional and the form can be submitted with empty fields 
`[Checklist p14: Form shouldn't be submitted if some of the fields are not filled]`
- Page shouldn't be reloaded [on form submit ](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)`[Checklist p15]`

**Comment by EugeneSherepa** [comment]
@33Orange, I don`t understand what is wrong with my js code to fix tabindex and submit button, would appriciate for help

**Comment by 33Orange** [comment]
> @33Orange, I don`t understand what is wrong with my js code to fix tabindex and submit button, would appriciate for help

Feel free to ask in slack qna chat about your problems.

**Review by 33Orange — CHANGES_REQUESTED** [review]
I see some fixes from your commit, but you didn't update the demo of website.

**Review by silchyn — CHANGES_REQUESTED** [review]
- Page shouldn't be reloaded [on form submit ](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)[Checklist p15]

**Review by silchyn — CHANGES_REQUESTED** [review]
- I can submit an empty form
- Form is not cleared on submit

**Review by silchyn — APPROVED** [review]

**Pull request closed without merging**
