### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Dorosh90**
-[DEMO LINK](https://Dorosh90.github.io/layout_miami/)

### CODE REVIEW

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Great job. Fix a few moments:
- fix the logo link. now it leads to the 404
image

- the close button in the menu and menu button in the header should be on the same position https://www.loom.com/share/474e80cc7de8497294de049e151da7b8
- make the message required too. and don't reload the page on form submitting
image

- use the image directly from the mobile to make it looks good
image

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good job! Some things to be improved 

1. fix background image 
image
you can try to play with background-size: contain(it'll broke view for start, but generally image will be positioned better :)

2.image is overlapping text on hover
image

**Review by sTorba24 — CHANGES_REQUESTED** [review]
background behaviour can be better 
image

it'll be checked by recruiter and sometime this background isn't well positioned

**Review by sTorba24 — CHANGES_REQUESTED** [review]
try to set 
background-position: 50% for >744
before background-position: 85% 50%

**Review by mykhalenych — APPROVED** [review]

**Review by marina-tilniak — APPROVED** [review]

**Pull request closed without merging**
