### PR TITLE
landing page for The Met

### PR DESCRIPTION
**Pull request by MartaChobaniuk**
- [DEMO LINK](https://martachobaniuk.github.io/layout_miami/)

### CODE REVIEW

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Good start, keep going!
- phone links lead to 404
image

**Review by mykhalenych — CHANGES_REQUESTED** [review]
nice work, we are waiting for the next sections

**Review by mykhalenych — CHANGES_REQUESTED** [review]
1. after click on links got 404 page
Screenshot 2023-04-24 at 17 24 33
2. add validation to inputs

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
nice work.
needs some improvements from [checklist](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)
- add hovers for phone, email, address
- Form shouldn't be submitted if some of the fields are not filled, apply validation for inputs.
- Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)
  for fix it add such code to main.js
  ```
    const form = document.querySelector('YOUR_FORM_SELECTOR');

    form.addEventListener('submit', (event) => {
       event.preventDefault();

       form.reset();
     });

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Good job! Let's improve some moments:
- no need to open a new tab on this button, just link to the top of the section
image

- there should be 72px side indent on the tab
image

- please compare images from this section with the mockup. They are too big in your page
image

- fix this section(tab)
image
image

- and this one too
image
image

**Pull request closed without merging**
