### PR TITLE
(BOSE) landing page

### PR DESCRIPTION
**Pull request by mxwolfy**
[DEMO LINK](https://mxwolfy.github.io/layout_miami/)

### CODE REVIEW

**Review by witflash — CHANGES_REQUESTED** [review]
Good start! 
Keep up the good work!

**Comment by VitaliyBondarenko1982** [comment]
Nice job!
Please fix 15 point in requirements.
Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)

**Comment by mxwolfy** [comment]
> houldn't be reloaded on form sub

Thanks, okay

**Comment by mxwolfy** [comment]
> Nice job! Please fix 15 point in requirements. Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)

Hello, could you check my landing page, please

**Pull request closed without merging**
