### PR TITLE
MyBike

### PR DESCRIPTION
**Pull request by MaksymBevskyi**
[DEMO LINK ](https://MaksymBevskyi.github.io/layout_miami/)

### CODE REVIEW

**Comment by MaksymBevskyi** [comment]
[DEMO LINK](https://MaksymBevskyi.github.io/layout_miami_bike/) Correct

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's to fix some mistakes
The phone number should not be transferred
image
When you click on mail, a window for sending a letter should appear
image

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
1. Page should not reloads on submit, also clear form fields on button click
image


2. Hide scroll when menu is open
image
image

**Review by Volodymyr-Melnyk-Fron10der — CHANGES_REQUESTED** [review]
1. don't see your solution
image

**Review by Volodymyr-Melnyk-Fron10der — APPROVED** [review]

**Pull request closed without merging**
