### PR TITLE
header was created

### PR DESCRIPTION
**Pull request by vanyachyzh**
[DEMO LINK](https://vanyachyzh.github.io/layout_miami/) 

something happened to my logo. it is not displayed on the screen in github pages but everything is okay on my pc

### CODE REVIEW

**Review by witflash — CHANGES_REQUESTED** [review]
Вітаю з початком!

Поки все ок.
Лише не забудь, що:
- при відкритті меню потрібно відключати скрол у сторінки;
- потрібно буде додати фавікон.

**Review by Anastasiia-Svintsova — CHANGES_REQUESTED** [review]
- Please, implement all sections and request the review after that

**Comment by TarasHoliuk** [comment]
About form:
image

- submit shouldn't lead to a 404 page
- submit shouldn't refresh page
- clear fields on submit

You might need to add a little piece of js code to fix it, ask in fe_chat if you need help with it

**Comment by TarasHoliuk** [comment]
Add hover effects on interactive elements (links, buttons) and images to make landing page more live

image

**Comment by TarasHoliuk** [comment]
Add logo via `img` tag instead of `css`

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Check comments

**Comment by VitaliyBondarenko1982** [comment]
1. Try to send form without message. It goes to 404 page
Screenshot from 2023-01-24 13-25-16

2. fix please some test errrors
Screenshot from 2023-01-24 13-11-49

**Comment by vanyachyzh** [comment]
> 1. Try to send form without message. It goes to 404 page
>    Screenshot from 2023-01-24 13-25-16
> 2. fix please some test errrors
>    Screenshot from 2023-01-24 13-11-49



> 1. Try to send form without message. It goes to 404 page
>    Screenshot from 2023-01-24 13-25-16
> 2. fix please some test errrors
>    Screenshot from 2023-01-24 13-11-49



> Add logo via `img` tag instead of `css`

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
hey! check this bug
https://user-images.githubusercontent.com/60295799/214528786-7331c767-c497-48de-a7cc-2fa9e6161c20.mov

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Demo Link not works. 
Try to remove type="image/x-icon" 
There was sometime problems with it.
https://mate-parttime.slack.com/archives/C048S1Q5C94/p1674637471475029

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
I can scroll your page with menu
Screenshot 2023-01-30 at 11 03 25 AM

fix it
good job!

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
Screenshot 2023-01-31 at 11 42 50 AM
I still can scroll your page with menu

**Comment by OlEzhA0** [comment]
Screenshot 2023-02-01 at 11 11 52 AM
hey! check this bug
when I reproduce it, I can't even close menu

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
hey! check issue with menu

https://user-images.githubusercontent.com/60295799/216000931-39b1ed34-7708-4c86-99ec-bf9ad80d5c1d.mov

**Review by mykhalenych — APPROVED** [review]

**Pull request closed without merging**
