### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by savchuksavchuk**
[DEMO LINK](https://savchuksavchuk.github.io/layout_miami/)

### CODE REVIEW

**Review by valerii-derkach — CHANGES_REQUESTED** [review]
prevent scrolling menu
https://www.loom.com/share/997dfd249ef44ffb9b45f9d080ae8856


scale is too large, let's reduce it, it is not ok when one picture overs another
image

add smooth for hover effect for the button

image

**Review by valerii-derkach — CHANGES_REQUESTED** [review]
did you deploy? nothing changed

**Comment by savchuksavchuk** [comment]
sorry, now it is deployed

**Review by marina-tilniak — CHANGES_REQUESTED** [review]
відправка форми не повинна перезавантажувати сторінку(https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) та після того як натиснули на кнопку поля форми мають ставати пустими

**Review by AlisaVlasova — CHANGES_REQUESTED** [review]
add smooth hover also here
image
image
image
image

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Make fields required

**Review by AlisaVlasova — APPROVED** [review]

**Pull request closed without merging**
