### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by BilokonYaroslav**
[DEMO LINK](https://BilokonYaroslav.github.io/layout_miami/)

### CODE REVIEW

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
Screenshot 2023-03-14 at 10 50 37 AM
it's shouldn't be all clickable area

change this hover effect a bit
https://user-images.githubusercontent.com/60295799/224947007-ee1413f6-bdc9-40d7-91f8-33d040f87661.mov

design:
Screenshot 2023-03-14 at 10 53 32 AM
your:
Screenshot 2023-03-14 at 10 53 46 AM

page shouldn't refresh after click on `Send` on form

check this bug
Screenshot 2023-03-14 at 10 54 53 AM

**Comment by BilokonYaroslav** [comment]
I have'nt last bug on my PC and by DEMO LINK. I use Chrome, maybe I should check on another browser?

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
To reproduce issue: Open menu and disable overflow. To fix - increase `z-index` for menu
2023-03-14_13h39_21

Add validation to form

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
almost done!

reset form after submit
input validation somehow not works. please check it.
Change text color on hover for phone, email and address

**Comment by BilokonYaroslav** [comment]
where I should change text color on hover for phone, email and address?

**Comment by VitaliyBondarenko1982** [comment]
> where I should change text color on hover for phone, email and address?

Screenshot from 2023-03-16 13-14-58

**Pull request closed without merging**
