### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rstarovoit**
- [DEMO LINK](https://rstarovoit.github.io/layout_miami/)

### CODE REVIEW

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
You forgot to reset `h1` default margins 

Link here in first block should redirect somewhere to map, over 50 ... link can be just a text. There is no need to redirect user to top of the page from every link. Same with links in Testimonials, redirect somewhere to social medias of this people or make just blue text from it

After form submit page was redirected to page with error, fix it

Also links in logo redirects to page with error, fix it

**Comment by rstarovoit** [comment]
> go redirects to page with error, fix it

**Comment by rstarovoit** [comment]
> You forgot to reset `h1` default margins
> 
> Link here in first block should redirect somewhere to map, over 50 ... link can be just a text. There is no need to redirect user to top of the page from every link. Same with links in Testimonials, redirect somewhere to social medias of this people or make just blue text from it
> 
> After form submit page was redirected to page with error, fix it
> 
> Also links in logo redirects to page with error, fix it

Thnks 4 feedback! All done as you commented)

**Review by OleksiiBlezniuk — COMMENTED** [review]
Approve, but I recommend you to add some hover effects to all blue links (for example make them darker). Also better to scale image in Testimonials instead of rotating - it will be more smooth and nice.

**Review by OleksiiBlezniuk — APPROVED** [review]
Please check previous comment

**Pull request closed without merging**
