### PR TITLE
The Met Landing

### PR DESCRIPTION
**Pull request by vintwp**
https://vintwp.github.io/layout_miami/

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
1. Add smooth animation on scroll
2. Page should not reloads on button click, also you need to clear form fields on button click
image
3. Add href to phone icon
smth like: href="tel:+1 234 5555-55-55"

4. Click on logo on main page and in menu leads to 404 page
image
5. Add href with phone number to this link
image
6. Add some hover effects to all intercative elements includes images in gallery
image
image

**Comment by vintwp** [comment]
Good Evening! Fixed landing according to your recommendations. But, I have some  questions:
1) Href into logo is `<a href=**"/"**>Logo</a>`, and i've not received 404. Should I put another link into href ?
2) Is better to use there div block with inner block ? Because phone logo has small sizes, and hover works incorrect (user couldn't click to phone number into label). What will you advice me, what shall i do? Thanks!
image

**Comment by YegorKorenkov** [comment]
> Good Evening! Fixed landing according to your recommendations. But, I have some questions:
> 
> 1. Href into logo is `<a href=**"/"**>Logo</a>`, and i've not received 404. Should I put another link into href ?
> 2. Is better to use there div block with inner block ? Because phone logo has small sizes, and hover works incorrect (user couldn't click to phone number into label). What will you advice me, what shall i do? Thanks!
>    image

Hi
1. U can pass # for preventing 404 error
2. Try to move your div with phones into block with phone icon and rewrite hover
image

**Review by YegorKorenkov — CHANGES_REQUESTED** [review]
1. Please fix link for home
image
2. Form shouldn't be submitted if some of the fields are not filled

**Review by slavanosatskyi — CHANGES_REQUESTED** [review]
1. Wrong font-weight

2. Too wide text 
Screenshot 2023-03-14 at 19 31 04
3. Too wide text
Screenshot 2023-03-14 at 19 31 33

**Comment by vintwp** [comment]
Hello. Thanks for your comment! I have some question too, if possible? Which is better way to limit title block width:
1) Use grid, and set necesssary columns (increase html)
2) Set the max-width for title block ? 
Thanks for your answers!

**Comment by nazarmatsevych** [comment]
> Which is better way to limit title block width:

Max width and for example margin: 0 auto for centering looks good.

Please next time ask your questions in fe_chat to solve them faster

**Pull request closed without merging**
