### PR TITLE
landing MyBike

### PR DESCRIPTION
**Pull request by misha-vynnyk**
https://misha-vynnyk.github.io/layout_mybike/

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good start.
Check click on logo - it follows on 404 page.
We are waiting next sections.

**Comment by misha-vynnyk** [comment]
I have a problem with the implementation of the tablet version. 
"grid-column" does not work correctly.

**Comment by misha-vynnyk** [comment]
I have a problem with the implementation of the tablet version.
"grid-column" does not work correctly.

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
Screenshot 2023-03-06 at 11 06 30 AM
mb center it

Gj! Waiting for next sections

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
add some hover effects to your images

Gj!
Screenshot 2023-03-07 at 11 19 26 AM

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. try to fix this overlapping 
image
2. and add hover to those photos

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
almost done!
needs some improvements from [checklist](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)
- Change text color on hover for phone, email and address
- after click on button nothing happens. 
   add validation for fields (required attribute) ans such code in main.js
   
   ```
   const form = document.querySelector('YOUR_FORM_SELECTOR');

  form.addEventListener('submit', (event) => {
    event.preventDefault();

    form.reset();
  });
```
- for send button add `cursor: pointer`

**Review by etojeDenys — CHANGES_REQUESTED** [review]
i  can't submit the form or the form does not reset after submitting

https://user-images.githubusercontent.com/70220667/228755922-f1b3a342-66f1-4957-9025-9fded84d72bb.mov

**Review by etojeDenys — APPROVED** [review]
awesome

**Pull request closed without merging**
