### PR TITLE
Mybike

### PR DESCRIPTION
**Pull request by d-beschastnyi**
[DEMO LINK](https://d-beschastnyi.github.io/layout_miami/)

### CODE REVIEW

**Comment by d-beschastnyi** [comment]
not a finale version

only header & menu was added

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Good job. Re-request review after you finish whole landing

**Comment by d-beschastnyi** [comment]
not a finale version

only about block was added

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- this hover effect moves the bottom section. fix it
https://www.loom.com/share/4a4a114bca224b2bb46994cc4251d65a

- make all fields required. and page shouldn't reload on submitting
image

- did you implement the changes for the tab screen? it look different on the mockup
image

- the header should be fit the screen height on the mobile
image

- fix this button on the mobile
image

**Review by qoa11a — APPROVED** [review]

**Pull request closed without merging**
