### PR TITLE
header block initial commit

### PR DESCRIPTION
**Pull request by olenitut**
[DEMO LINK](https://olenitut.github.io/layout_bose/)

### CODE REVIEW

**Review by alexandra-protyanova — CHANGES_REQUESTED** [review]
Request review when everything will be implemented

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. 404 after click on logo
2. Add hover effects to this images 
image
3. Make scale smaller to avoid overlapping
4. Form should reset after submit

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. Add some hover effects for this links. But not a scale (change color for example)
2. Make fields required

**Comment by olenitut** [comment]
>

**Comment by olenitut** [comment]
They did have requred but i prevented default with js. Will fix with js

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- It isn't a really good idea to clear the form after the message of the required field

- And it will be good to add some hover effects to links

**Review by liliia-livandovskaya — APPROVED** [review]
Great job! don't forget to add hover effects to the links Screenshot 2022-11-07 at 18 26 53

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
1. When I open menu and click on logo - it's redirected me to 404
2. bug with textarea. Please block resize possibility here
Screenshot 2023-02-16 at 10 05 18 AM
3. I can't hover on phone number to copy it
Screenshot 2023-02-16 at 10 07 11 AM
4. mac users can find next bug
Screenshot 2023-02-16 at 10 08 26 AM

**Pull request closed without merging**
