### PR TITLE
Header and menu was created

### PR DESCRIPTION
**Pull request by NazariiAlieksieiev**
[DEMO LINK](https://NazariiAlieksieiev.github.io/layout_miami/)

I added fonts local and with link. It`s gives my possibility working without connection to internet.

### CODE REVIEW

**Review by AlisaVlasova — CHANGES_REQUESTED** [review]
keep going!)

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
Great job! Pay attention to the following points:

1. There should not be 404 errors
Screenshot 2022-12-19 at 13 14 16

Screenshot 2022-12-19 at 13 14 51

Screenshot 2022-12-19 at 13 15 00

Screenshot 2022-12-19 at 13 14 51

2. Add contact us block 
Screenshot 2022-12-19 at 13 16 32

3. Add a hover effect on blocks with pictures 
Screenshot 2022-12-19 at 13 15 25

4. There should not be a button on his photo, remove it 

Screenshot 2022-12-19 at 13 16 08

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
Screenshot 2022-12-20 at 2 39 12 PM
the form must be cleared after submission

Screenshot 2022-12-20 at 2 39 56 PM
Google Maps should open in a new tab

Screenshot 2022-12-20 at 2 40 44 PM
add validation for email

**Comment by OlEzhA0** [comment]
if you have any questions just ping us in fe_chat

**Review by witflash — CHANGES_REQUESTED** [review]
Looks great!
But here the last improvements:
> 14. Form shouldn't be submitted if some of the fields are not filled
> 17. Fix menu for small screens (if there is not enough space for all the menu items)
image

**Review by witflash — APPROVED** [review]
Pretty well! Good job! 👍

**Pull request closed without merging**
