### PR TITLE
Header mobile

### PR DESCRIPTION
**Pull request by oksanatytanych**

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Please provide a Demo Link

**Comment by oksanatytanych** [comment]
- [DEMO LINK]  (https://oksanatytanych.github.io/layout_miami/)
- [BOSE landing]  (https://www.figma.com/file/OMjQNb3hg1LKMV4OwyQ3Ao/BOSE?node-id=0%3A1)

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Fine!)

Fixes:
1) Logo shouldn't lead to 404 page
2) Add favicon
3) According to figma project - menu should be with a purple background, not green 

Keep going!)

**Review by mykhalenych — CHANGES_REQUESTED** [review]
Logo still navigate to 404 page

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Images not increase on hover
Location-related addresses opens in current tab
Form can be submitted without message
Try adapt page for 1920*1080 resolution

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
1. When I click on Logo in menu, it's redirected me to 404
2. please check and change your hover effect, you can increase your image inside your container
Screenshot 2023-01-18 at 8 17 20 PM
3. form submission shouldn't refresh page

**Review by witflash — CHANGES_REQUESTED** [review]
Please add form validation for all form field (name, email, message)

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
1. prevent page refresh after form submission 
2. check this bug
Screenshot 2023-01-24 at 10 59 55 AM

**Comment by TarasHoliuk** [comment]
After preventing page refresh after form submission need to clear form values (just add `evet.target.reset()` next to preventDefault)

Also, I'd recommend using the same transition-duration value everywhere on the page, but not critically (up to you)

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
You did an amazing job! :fire: 
I've added 2 small comments to improve your landing :slightly_smiling_face:

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
remove outlines from inputs
Screenshot 2023-02-01 at 10 30 05 AM

check this bug
Screenshot 2023-02-01 at 10 31 54 AM

**Review by IvanFesenko — APPROVED** [review]
Well done

**Pull request closed without merging**
