### PR TITLE
Bose Landing is created

### PR DESCRIPTION
**Pull request by iryna-serniuk**
[DEMO LINK](https://iryna-serniuk.github.io/layout_miami/)

### CODE REVIEW

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
1. add favicon
2. here is hard to see phone number
Screenshot 2022-12-24 at 10 37 49 PM
3. not consistent distance 
Screenshot 2022-12-24 at 10 39 11 PM
4. View All button looks weird and has no any effects and even cursor pointer
Screenshot 2022-12-24 at 10 41 39 PM
5. Address link should open in new tab
6. Form shouldn't reload page
7. add spaces like in design for blocks `Why buy direct
from Bose`, `Contact Us`

**Comment by iryna-serniuk** [comment]
> 

Ok, I'll fix it. I haven't finished it yet.

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
1. When I click on logo it's redirected me to 404
2. This effects on images looks weird
Screenshot 2022-12-27 at 12 44 14 PM
3. After form submission it's should be clear and page shouldn't refresh
4. 1023px screen shouldn't looks like this
Screenshot 2022-12-27 at 12 47 05 PM

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
You have 2 opened PRs. Close one of them. https://github.com/mate-academy/layout_miami/pull/1911

**Pull request closed without merging**
